### ISSUE TITLE
Add support for Sass

### ISSUE THREAD

**Issue by davidblurton** [aranja/gulp-base#1]
You can just create files with the right extension and gulp with build them.

**Comment by rthor** [comment]
Why SASS? Shouldn't we rather pick a favored preprocessor instead of having to maintain two or more? I don't think having a base that tries to solve everything is a good idea in the long run.

**Comment by davidblurton** [comment]
I agree we should pick one. I find it hard to switch between them. 

Should less or sass be the official Aranja css preprocessor?

**Comment by eirikurn** [comment]
We decided a while back that less should be our processor of choice. Mainly as it's quick, consistent, extensible with JS and does not have Ruby version hell :)

But we have probably switched in every project, and for 2015, is it time for rework or stylus?

... Kidding

**Comment by davidblurton** [comment]
Less it is then
