### ISSUE TITLE
Add a linter task

### ISSUE THREAD

**Issue by davidblurton** [aranja/gulp-base#12]

**Comment by eirikurn** [comment]
Would be nice to setup some sweet eslint config. It might conflict with ES6 or React, but I think support is coming.

**Comment by rthor** [comment]
I'ld prefer JSCS with the `google` preset. http://jscs.info/overview.html

**Comment by davidblurton** [comment]
Sounds good. Put it in and run a self test.

**Comment by eirikurn** [comment]
Hm, afaik jscs is more of a style checker than a linter. I think many use both jscs and *lint, but I might be wrong.

Reason I like eslint is it is pretty easy to extend to do all kinds of specific checks, i.e. aranjalint :)

**Comment by rthor** [comment]
Yeah that's absolutely true. I think a mix of both would be kind'a cool. I'll create a pull request.

**Comment by eirikurn** [comment]
As I mentioned tonight, I'm fine with keeping what we have already with jshint and adding jscs, until eshint fixes their es6 game.

Btw, does jscs support es6 ok?

**Comment by rthor** [comment]
Added in a57c5e72e4277c11129de3d3eddc537021021ac4
