### ISSUE TITLE
Rename (or alias) tasks by semantic, not by tool

### ISSUE THREAD

**Issue by eirikurn** [aranja/gulp-base#32]
The point is to keep the cli commands the same across projects even though the tools change. 
- [ ] browserify -> scripts
- [ ] less -> styles
- [ ] jade -> templates

These are the names I've seen before and like the most, but another option is to name them after the output file type, `js`, `css`, `html`.

They can also be wrappers for other tasks, ie `scripts` can run `scripts-main`, `scripts-browserify`, `scripts-vendor` etc.

**Comment by rthor** [comment]
:+1:
