### ISSUE TITLE
Regression: Livereload doesn't work

### ISSUE THREAD

**Issue by eirikurn** [aranja/gulp-base#35]
Since gulp-connect is not injecting livereload script anymore.

**Comment by rthor** [comment]
This works on my end... You sure that the browser extension was active?

**Comment by eirikurn** [comment]
I don't use a browser extension. Before the server would inject the
livereload script.

**Comment by rthor** [comment]
Ahh ok I always use the extension so I never have had this prob. Will look into it.

**Comment by thorsteinsson** [comment]
We've got browsersync now.
